- name: ubuntu | Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: ubuntu | Apt update
  ansible.builtin.apt:
    upgrade: distbitMQ Management Console

